const products = [
  //Sản phẩm mới
  {
    id: "ao-polo-dong-phuc-cong-ty-aircool-",
    name: "Áo polo đồng phục công ty aircool",
    image: "image/ao-polo-dong-phuc-cong-ty-aircool-03-mau-bich-1.jpg",
    desc: "Áo polo được làm từ chất liệu mát, mềm mại và thoáng khí, mang lại cảm giác dễ chịu khi mặc trong thời gian dài. Vải có khả năng thấm hút mồ hôi tốt, co giãn nhẹ và hạn chế bí nóng, phù hợp cho thời tiết hằng ngày cũng như các hoạt động ngoài trời.",
    type: "new",
  },
  {
    id: "ao-dong-phuc-cong-ty-prime-cotton-mau-ya-dam-phoi-tay-vai-trang-gao",
    name: "Áo đồng phục công ty Prime cotton xanh phối tay vải trắng gạo",
    image:
      "image/ao-dong-phuc-cong-ty-prime-cotton-mau-ya-dam-phoi-tay-vai-trang-gao-6.jpg",
    desc: "Áo thun được làm từ chất liệu mát, mềm mại và thoáng khí, mang lại cảm giác dễ chịu khi mặc trong thời gian dài. Vải có khả năng thấm hút mồ hôi tốt, co giãn nhẹ và hạn chế bí nóng, phù hợp cho thời tiết hằng ngày cũng như các hoạt động ngoài trời.",
    type: "new",
  },
  {
    id: "dong-phuc-ecotton-vang-cuc",
    name: "Đồng phục công ty ecotton màu vàng cúc",
    image: "image/ao-dong-phuc-cong-ty-ecotton-2-mau-vang-cuc.jpg",
    desc: "Áo thun được làm từ chất liệu mát, mềm mại và thoáng khí, mang lại cảm giác dễ chịu khi mặc trong thời gian dài. Vải có khả năng thấm hút mồ hôi tốt, co giãn nhẹ và hạn chế bí nóng, phù hợp cho thời tiết hằng ngày cũng như các hoạt động ngoài trời.",
    type: "new",
  },
  {
    id: "cover-danh-muc-dong-phuc-teambuilding",
    name: "Đồng phục teambuilding công ty trắng đỏ",
    image: "image/cover-danh-muc-dong-phuc-teambuilding.jpg",
    desc: "Áo thun được làm từ chất liệu mát, mềm mại và thoáng khí, mang lại cảm giác dễ chịu khi mặc trong thời gian dài. Vải có khả năng thấm hút mồ hôi tốt, co giãn nhẹ và hạn chế bí nóng, phù hợp cho thời tiết hằng ngày cũng như các hoạt động ngoài trời..",
    type: "new",
  },
  {
    id: "cover-danh-muc-dong-phuc-ao-polo",
    name: "Đồng phục áo polo công ty trắng cánh tay xanh",
    image: "image/cover-danh-muc-dong-phuc-ao-polo.jpg",
    desc: "Áo thun được làm từ chất liệu mát, mềm mại và thoáng khí, mang lại cảm giác dễ chịu khi mặc trong thời gian dài. Vải có khả năng thấm hút mồ hôi tốt, co giãn nhẹ và hạn chế bí nóng, phù hợp cho thời tiết hằng ngày cũng như các hoạt động ngoài trời.",
    type: "new",
  },
  //Sản phẩm cũ
  {
    id: "ao-thun-polo-do-do-co-tim",
    name: "Áo thun đồng phục polo cổ tím màu đỏ đô",
    image: "image/products/ao-thun-dong-phuc-polo-co-tim-mau-do-do-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "thun-polo",
  },
  {
    id: "dong-phuc-hop-lop-10-nam",
    name: "Đồng phục họp lớp 10 năm cổ tròn màu trắng",
    image: "image/products/dong-phuc-hop-lop-10-nam-co-tron-mau-trang-8.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-hop-lop-15-nam",
    name: "Đồng phục họp lớp 15 năm màu biển nhạt phối vải",
    image:
      "image/products/dong-phuc-hop-lop-15-nam-mau-bien-nhat-phoi-vai-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-hop-lop-25-nam",
    name: "Đồng phục họp lớp 25 năm trường THPT Nguyễn Huệ",
    image:
      "image/products/dong-phuc-hop-lop-25-nam-truong-thpt-nguyen-hue-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-hop-lop-30-nam-dhkt",
    name: "Đồng phục họp lớp 30 năm đại học kinh tế quốc dân",
    image:
      "image/products/dong-phuc-hop-lop-30-nam-dai-hoc-kinh-te-quoc-dan-8.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-lop-dai-hoc-KHXHVNV",
    name: "Đồng phục lớp đại học KHXH và NV",
    image:
      "image/products/dong-phuc-hop-lop-dai-hoc-khoa-hoc-xa-hoi-va-nhan-van-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hoc-sinh",
  },
  {
    id: "dong-phuc-mam-non-co-tron-mau-xanh-bien-nhat",
    name: "Đồng phục mầm non cổ tròn màu xanh biển nhạt",
    image: "image/products/dong-phuc-mam-non-co-tron-mau-xanh-bien-nhat-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-co-tron-mau-xanh-den",
    name: "Đồng phục mầm non cổ tròn màu xanh đen",
    image: "image/products/dong-phuc-mam-non-co-tron-mau-xanh-den-8.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-co-tron-mau-xanh-iris",
    name: "Đồng phục mầm non cổ tròn màu xanh Iris",
    image: "image/products/dong-phuc-mam-non-co-tron-mau-xanh-iris-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-mau-cam-phoi-kem-cheese",
    name: "Đồng phục mầm non cam phối kem cheese",
    image: "image/products/dong-phuc-mam-non-mau-cam-phoi-kem-cheese-7.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-mau-do-do-phoi-xanh-den",
    name: "Đồng phục mầm non màu đỏ đô phối xanh đen",
    image: "image/products/dong-phuc-mam-non-mau-do-do-phoi-xanh-den-7.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-mau-ruoc-hong-phoi-trang-gao",
    name: "Đồng phục mầm non màu ruốc hồng phối trắng gạo",
    image:
      "image/products/dong-phuc-mam-non-mau-ruoc-hong-phoi-trang-gao-3.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "ao-dong-phuc-pickleball-thuong-hieu-momo",
    name: "Áo đồng phục pickleball thương hiệu momo",
    image: "image/products/ao-dong-phuc-pickleball-thuong-hieu-momo.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "the-thao",
  },
  {
    id: "ao-polo-dong-phuc-sun-world-3",
    name: "Áo polo đồng phục Sun World",
    image: "image/products/ao-polo-dong-phuc-sun-world-3.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "cong-ty",
  },
  {
    id: "ao-polo-dong-phuc-vietinbank-4",
    name: "Áo polo đồng phục Viettinbank",
    image: "image/products/ao-polo-dong-phuc-vietinbank-4.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "cong-ty",
  },
  {
    id: "ao-teambuilding-phoi-mau-thoi-trang-1",
    name: "Áo teambuiding phối màu thời trang",
    image: "image/products/ao-teambuilding-phoi-mau-thoi-trang-1.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "team-building",
  },
];
