const products = [
  {
    id: "dong-phuc-ecotton-mau-do",
    name: "Đồng phục công ty ecotton màu đỏ",
    image: "image/ao-dong-phuc-cong-ty-ecotton-2-mau-do.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "new",
  },
  {
    id: "dong-phuc-ecotton-gao-trang",
    name: "Đồng phục công ty ecotton màu gạo phối trắng",
    image: "image/ao-dong-phuc-cong-ty-ecotton-2-mau-trang-gao-phoi-trang.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "new",
  },
  {
    id: "dong-phuc-ecotton-vang-cuc",
    name: "Đồng phục công ty ecotton màu vàng cúc",
    image: "image/ao-dong-phuc-cong-ty-ecotton-2-mau-vang-cuc.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "new",
  },
  {
    id: "dong-phuc-ecotton-xanh-den",
    name: "Đồng phục công ty ecotton màu xanh đen",
    image: "image/ao-dong-phuc-cong-ty-ecotton-2-mau-xanh-den.png",
    desc: "Chất liệu cotton thoáng mát...",
    type: "new",
  },
  {
    id: "ao-khoac-dong-phuc-san-pham-chinh",
    name: "Áo khoác đồng phục",
    image: "image/ao-khoac-dong-phuc-dong-san-pham-chinh.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "new",
  },
  {
    id: "ao-thun-polo-do-do-co-tim",
    name: "Áo thun đồng phục polo cổ tím màu đỏ đô",
    image: "image/products/ao-thun-dong-phuc-polo-co-tim-mau-do-do-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "thun-polo",
  },
  {
    id: "dong-phuc-hop-lop-10-nam",
    name: "Đồng phục họp lớp 10 năm cổ tròn màu trắng",
    image: "image/products/dong-phuc-hop-lop-10-nam-co-tron-mau-trang-8.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-hop-lop-15-nam",
    name: "Đồng phục họp lớp 15 năm màu biển nhạt phối vải",
    image:
      "image/products/dong-phuc-hop-lop-15-nam-mau-bien-nhat-phoi-vai-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-hop-lop-25-nam",
    name: "Đồng phục họp lớp 25 năm trường THPT Nguyễn Huệ",
    image:
      "image/products/dong-phuc-hop-lop-25-nam-truong-thpt-nguyen-hue-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-hop-lop-30-nam-dhkt",
    name: "Đồng phục họp lớp 30 năm đại học kinh tế quốc dân",
    image:
      "image/products/dong-phuc-hop-lop-30-nam-dai-hoc-kinh-te-quoc-dan-8.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hop-lop",
  },
  {
    id: "dong-phuc-lop-dai-hoc-KHXHVNV",
    name: "Đồng phục lớp đại học KHXH và NV",
    image:
      "image/products/dong-phuc-hop-lop-dai-hoc-khoa-hoc-xa-hoi-va-nhan-van-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "hoc-sinh",
  },
  {
    id: "dong-phuc-mam-non-co-tron-mau-xanh-bien-nhat",
    name: "Đồng phục mầm non cổ tròn màu xanh biển nhạt",
    image: "image/products/dong-phuc-mam-non-co-tron-mau-xanh-bien-nhat-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-co-tron-mau-xanh-den",
    name: "Đồng phục mầm non cổ tròn màu xanh đen",
    image: "image/products/dong-phuc-mam-non-co-tron-mau-xanh-den-8.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-co-tron-mau-xanh-iris",
    name: "Đồng phục mầm non cổ tròn màu xanh Iris",
    image: "image/products/dong-phuc-mam-non-co-tron-mau-xanh-iris-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-mau-cam-phoi-kem-cheese",
    name: "Đồng phục mầm non cam phối kem cheese",
    image: "image/products/dong-phuc-mam-non-mau-cam-phoi-kem-cheese-7.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-mau-do-do-phoi-xanh-den",
    name: "Đồng phục mầm non màu đỏ đô phối xanh đen",
    image: "image/products/dong-phuc-mam-non-mau-do-do-phoi-xanh-den-7.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-mam-non-mau-ruoc-hong-phoi-trang-gao",
    name: "Đồng phục mầm non màu ruốc hồng phối trắng gạo",
    image:
      "image/products/dong-phuc-mam-non-mau-ruoc-hong-phoi-trang-gao-3.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "mam-non",
  },
  {
    id: "dong-phuc-vest-cong-so-nam-nu-elite-mau-be",
    name: "Vest công sở nam nữ elite màu be",
    image: "image/products/dong-phuc-vest-cong-so-nam-nu-elite-mau-be-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "cong-so",
  },
  {
    id: "vest-dong-phuc-cong-so-nam-nu-suittex-li-mau-ghi",
    name: "Vest đồng phục công sở nam nữ suittex li màu ghi",
    image:
      "image/products/vest-dong-phuc-cong-so-nam-nu-suittex-li-mau-ghi-2.jpg",
    desc: "Chất liệu cotton thoáng mát...",
    type: "old",
    category: "cong-so",
  },
];
